font_family        Geist Mono 
bold_font          Geist Mono 
italic_font        Geist Mono 
bold_italic_font   Geist Mono 

font_size 14.0
disable_ligatures never

window_padding_width 0
background_opacity 0.92
hide_window_decorations yes
shell_integration enabled

window_border_width 0
window_border_active_color #C0C0C0
window_border_inactive_color #505050
window_padding_width 0
window_padding_height 0

map cmd+plus            change_font_size all +2.0
map cmd+minus           change_font_size all -2.0
map cmd+0               change_font_size all 0

allow_remote_control yes
scrollback_lines 20000
include ./cherry-midnight.conf

# cursor none
# cursor_text_color background

