# Tmux Config
set -g default-terminal "screen-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Start window numbering at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

# The default key to split window panes horizontally is " and vertically is % so  replace them with
unbind %
bind | split-window -h

unbind '"'
bind _ split-window -v

unbind r
bind r source-file ~/.tmux.conf

## All these can be used only after the prefix which is Ctrl + A
## add some bindings to resize bw panes

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z 5

# Switch tmux panes with Alt+Arrows (no prefix needed)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

### Switch tmux windows with Alt+Number (no prefix needed)
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i' 

# set -g @plugin 'catppuccin/tmux'

# Plugins
set -g @plugin 'tmux-plugins/tpm'

## Themes
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @tokyo-night-tmux_theme default    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1

set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_pane_id_style hide
set -g @tokyo-night-tmux_zoom_id_style hide

# set -g @tokyo-night-tmux_show_datetime 1 # show datetime in status bar

set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'

set -g @tokyo-night-tmux_show_hostname 0
# Initialize TPM (keep at bottom)
run-shell '~/.tmux/plugins/tpm/tpm'
